name: Build Environment
inputs:
  PYTHON_VERSION:
    required: true
    type: string
runs:
  using: composite
  shell: bash
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.PYTHON_VERSION }}
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Chapter02/requirements.txt
        pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #if [ -f ./Chapter02/requirements.txt ]; then pip install -r ./Chapter02/requirements.txt; fi