name: Push To Feature Branch
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  approval:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push'}}
    environment: |-
      ${{
        github.ref_name == 'main' && 'deploy-higher-environment'
        || github.ref_name == 'develop' && 'deploy-higher-environment'
        || 'deploy-dev'
      }}
    steps:
      - name: Dummy Step
        run: |
          echo "Deploy Approval"
  linting:
    needs:
      - approval
    uses: ./.github/workflows/linting.yml
  tests:
    needs:
      - linting
    uses: ./.github/workflows/unit_tests.yml