name: PR to Develop or Main branch
on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
jobs:
  approval:
    uses: ./.github/workflows/approval.yml
  linting:
    needs:
      - approval
    uses: ./.github/workflows/linting.yml
  tests:
    needs:
      - linting
    uses: ./.github/workflows/unit_tests.yml