name: Push To Feature Branch
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Build Env
        uses: ./.github/workflows/needs_approval/
  linting:
    uses: ./.github/workflows/linting.yml
  tests:
    needs:
      - linting
    uses: ./.github/workflows/unit_tests.yml