name: Push To Feature Branch
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  approval:
    uses: ./.github/workflows/approval.yml
  linting:
    runs-on: ubuntu-latest
    needs:
      - approval
    steps:
      - name: Linting
        uses: ./.github/workflows/linting.yml
      - name: Tests
        uses: ./.github/workflows/unit_tests.yml