name: Run unit tests
on:
  workflow_call:
jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Test with pytest
          run: |
            pytest
          working-directory: Chapter02